# Generated by Django 3.0.3 on 2020-06-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0004_auto_20200625_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='respmicro',
            name='image',
            field=models.ImageField(null=True, upload_to='set_images'),
        ),
    ]
