# Generated by Django 3.0.3 on 2020-07-03 21:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0005_respmicro_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respmicro',
            name='image',
        ),
        migrations.AlterField(
            model_name='respmicro',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RespMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('respMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.RespMicro')),
            ],
        ),
    ]
