# Generated by Django 3.0.3 on 2020-07-03 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20200704_0047'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respmicro',
            name='images',
        ),
        migrations.AddField(
            model_name='respmicroimage',
            name='respMicro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.RespMicro'),
        ),
    ]
