# Generated by Django 3.0.3 on 2020-07-03 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0008_auto_20200704_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='respmicro',
            name='image',
            field=models.ImageField(null=True, upload_to=leads.models.upload_path),
        ),
        migrations.AlterField(
            model_name='respmicro',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='RespMicroImage',
        ),
    ]
