# Generated by Django 3.0.3 on 2020-07-03 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0009_auto_20200704_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, max_length=10000, null=True, upload_to=leads.models.upload_path)),
            ],
        ),
        migrations.AlterField(
            model_name='respmicro',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RespMicroUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='respmicro',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RespMicro', to='leads.RespMicroImage'),
        ),
    ]
