# Generated by Django 3.0.3 on 2020-07-04 01:31

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_auto_20200704_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=leads.models.upload_path),
        ),
    ]
