# Generated by Django 3.0.3 on 2020-07-04 19:31

from django.db import migrations, models
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_auto_20200704_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respmicroimage',
            name='respMicro',
        ),
        migrations.AddField(
            model_name='respmicro',
            name='images',
            field=models.ManyToManyField(related_name='set_imgs', to='leads.RespMicroImage'),
        ),
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=leads.models.upload_path),
        ),
    ]
