# Generated by Django 3.0.3 on 2020-07-04 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_auto_20200704_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respmicro',
            name='images',
        ),
        migrations.AddField(
            model_name='respmicroimage',
            name='respMicro',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='leads.RespMicro'),
        ),
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
