# Generated by Django 3.0.3 on 2020-07-04 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_auto_20200704_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respmicro',
            old_name='author',
            new_name='user',
        ),
    ]
