# Generated by Django 3.0.3 on 2020-07-04 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_auto_20200704_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respmicro',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='testing/'),
        ),
    ]
