# Generated by Django 3.0.3 on 2020-07-04 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_auto_20200705_0235'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respmicro',
            old_name='author',
            new_name='user',
        ),
    ]
