# Generated by Django 3.0.3 on 2020-07-05 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_auto_20200705_0237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respmicroimage',
            old_name='image',
            new_name='images',
        ),
    ]
