# Generated by Django 3.0.3 on 2020-07-05 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import leads.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0019_auto_20200705_0303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respmicro',
            name='user',
        ),
        migrations.AddField(
            model_name='respmicro',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='respmicro',
            name='images',
            field=models.ImageField(null=True, upload_to=leads.models.upload_path),
        ),
        migrations.DeleteModel(
            name='RespMicroImage',
        ),
    ]
