# Generated by Django 3.0.3 on 2020-07-05 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0020_auto_20200705_0339'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='respmicro',
            name='author',
        ),
        migrations.RemoveField(
            model_name='respmicro',
            name='images',
        ),
        migrations.AddField(
            model_name='respmicro',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='RespMicroUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='RespMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='testing/')),
                ('respMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='leads.RespMicro')),
            ],
        ),
    ]
