# Generated by Django 3.0.3 on 2020-07-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_respmicronotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testing4/'),
        ),
    ]
