# Generated by Django 3.0.3 on 2020-07-30 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20200730_0734'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respmicronotes',
            old_name='content',
            new_name='noteContent',
        ),
        migrations.RenameField(
            model_name='respmicronotes',
            old_name='x_dim',
            new_name='x',
        ),
        migrations.RenameField(
            model_name='respmicronotes',
            old_name='y_dim',
            new_name='y',
        ),
    ]
