# Generated by Django 3.0.3 on 2020-08-05 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20200730_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='respmicro',
            old_name='owner_id',
            new_name='owner',
        ),
    ]
