# Generated by Django 3.0.3 on 2020-08-10 23:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0006_auto_20200805_0501'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Repiratory/Clinical')),
                ('respClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.RespClinical')),
            ],
        ),
        migrations.CreateModel(
            name='RespCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Repiratory/Cytology')),
                ('respCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.RespCyto')),
            ],
        ),
        migrations.CreateModel(
            name='RespHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Repiratory/Histology')),
                ('respHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.RespHisto')),
            ],
        ),
        migrations.CreateModel(
            name='RespImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Repiratory/Imaging')),
                ('respImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.RespImaging')),
            ],
        ),
        migrations.CreateModel(
            name='RespPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RespPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Repiratory/Pathology')),
                ('respPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.RespPatho')),
            ],
        ),
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Repiratory/Microbiology'),
        ),
        migrations.CreateModel(
            name='RespPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('respPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.RespPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='RespImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('respImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.RespImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='RespHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('respHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.RespHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='RespCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('respCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.RespCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='RespClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('respClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.RespClinicalImage')),
            ],
        ),
    ]
