# Generated by Django 3.0.3 on 2020-08-11 18:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0007_auto_20200811_0231'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardioClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardioClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Cardiology/Clinical')),
                ('cardioClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.CardioClinical')),
            ],
        ),
        migrations.CreateModel(
            name='CardioCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardioCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Cardiology/Cytology')),
                ('cardioCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.CardioCyto')),
            ],
        ),
        migrations.CreateModel(
            name='CardioHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardioHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Cardiology/Histology')),
                ('cardioHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.CardioHisto')),
            ],
        ),
        migrations.CreateModel(
            name='CardioImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardioImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Cardiology/Imaging')),
                ('cardioImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.CardioImaging')),
            ],
        ),
        migrations.CreateModel(
            name='CardioMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardioMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Cardiology/Microbiology')),
                ('cardioMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.CardioMicro')),
            ],
        ),
        migrations.CreateModel(
            name='CardioPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cardioPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardioPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Cardiology/Pathology')),
                ('cardioPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.CardioPatho')),
            ],
        ),
        migrations.CreateModel(
            name='EndoClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndoClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Endocrine/Clinical')),
                ('endoClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.EndoClinical')),
            ],
        ),
        migrations.CreateModel(
            name='EndoCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndoCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Endocrine/Cytology')),
                ('endoCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.EndoCyto')),
            ],
        ),
        migrations.CreateModel(
            name='EndoHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndoHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Endocrine/Histology')),
                ('endoHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.EndoHisto')),
            ],
        ),
        migrations.CreateModel(
            name='EndoImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndoImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Endocrine/Imaging')),
                ('endoImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.EndoImaging')),
            ],
        ),
        migrations.CreateModel(
            name='EndoMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndoMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Endocrine/Microbiology')),
                ('endoMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.EndoMicro')),
            ],
        ),
        migrations.CreateModel(
            name='EndoPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='endoPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EndoPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Endocrine/Pathology')),
                ('endoPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.EndoPatho')),
            ],
        ),
        migrations.CreateModel(
            name='GastroClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastroClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastroClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Gastrointestinal/Clinical')),
                ('gastroClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GastroClinical')),
            ],
        ),
        migrations.CreateModel(
            name='GastroCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastroCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastroCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Gastrointestinal/Cytology')),
                ('gastroCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GastroCyto')),
            ],
        ),
        migrations.CreateModel(
            name='GastroHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastroHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastroHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Gastrointestinal/Histology')),
                ('gastroHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GastroHisto')),
            ],
        ),
        migrations.CreateModel(
            name='GastroImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastroImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastroImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Gastrointestinal/Imaging')),
                ('gastroImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GastroImaging')),
            ],
        ),
        migrations.CreateModel(
            name='GastroMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastroMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastroMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Gastrointestinal/Microbiology')),
                ('gastroMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GastroMicro')),
            ],
        ),
        migrations.CreateModel(
            name='GastroPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gastroPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GastroPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Gastrointestinal/Pathology')),
                ('gastroPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GastroPatho')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genitoClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenitoClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Genitourinary/Clinical')),
                ('genitoClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GenitoClinical')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genitoCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenitoCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Genitourinary/Cytology')),
                ('genitoCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GenitoCyto')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genitoHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenitoHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Genitourinary/Histology')),
                ('genitoHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GenitoHisto')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genitoImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenitoImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Genitourinary/Imaging')),
                ('genitoImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GenitoImaging')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genitoMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenitoMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Genitourinary/Microbiology')),
                ('genitoMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GenitoMicro')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='genitoPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GenitoPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Genitourinary/Pathology')),
                ('genitoPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.GenitoPatho')),
            ],
        ),
        migrations.CreateModel(
            name='HemaClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hemaClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HemaClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/HemeOnc/Clinical')),
                ('hemaClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.HemaClinical')),
            ],
        ),
        migrations.CreateModel(
            name='HemaCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hemaCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HemaCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/HemeOnc/Cytology')),
                ('hemaCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.HemaCyto')),
            ],
        ),
        migrations.CreateModel(
            name='HemaHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hemaHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HemaHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/HemeOnc/Histology')),
                ('hemaHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.HemaHisto')),
            ],
        ),
        migrations.CreateModel(
            name='HemaImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hemaImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HemaImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/HemeOnc/Imaging')),
                ('hemaImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.HemaImaging')),
            ],
        ),
        migrations.CreateModel(
            name='HemaMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hemaMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HemaMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/HemeOnc/Microbiology')),
                ('hemaMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.HemaMicro')),
            ],
        ),
        migrations.CreateModel(
            name='HemaPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hemaPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HemaPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/HemeOnc/Pathology')),
                ('hemaPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.HemaPatho')),
            ],
        ),
        migrations.CreateModel(
            name='MSKClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mskClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSKClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/MSK/Clinical')),
                ('mskClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.MSKClinical')),
            ],
        ),
        migrations.CreateModel(
            name='MSKCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mskCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSKCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/MSK/Cytology')),
                ('mskCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.MSKCyto')),
            ],
        ),
        migrations.CreateModel(
            name='MSKHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mskHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSKHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/MSK/Histology')),
                ('mskHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.MSKHisto')),
            ],
        ),
        migrations.CreateModel(
            name='MSKImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mskImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSKImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/MSK/Imaging')),
                ('mskImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.MSKImaging')),
            ],
        ),
        migrations.CreateModel(
            name='MSKMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mskMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSKMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/MSK/Microbiology')),
                ('mskMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.MSKMicro')),
            ],
        ),
        migrations.CreateModel(
            name='MSKPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mskPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MSKPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/MSK/Pathology')),
                ('mskPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.MSKPatho')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroClinical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuroClinical', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroClinicalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Neurology/Clinical')),
                ('neuroClinical', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.NeuroClinical')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroCyto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuroCyto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroCytoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Neurology/Cytology')),
                ('neuroCyto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.NeuroCyto')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroHisto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuroHisto', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroHistoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Neurology/Histology')),
                ('neuroHisto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.NeuroHisto')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroImaging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuroImaging', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroImagingImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Neurology/Imaging')),
                ('neuroImaging', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.NeuroImaging')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroMicro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuroMicro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroMicroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Neurology/Microbiology')),
                ('neuroMicro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.NeuroMicro')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroPatho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='neuroPatho', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NeuroPathoImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='Blocks/Neurology/Pathology')),
                ('neuroPatho', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setImages', to='backend.NeuroPatho')),
            ],
        ),
        migrations.AlterField(
            model_name='respclinicalimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Respiratory/Clinical'),
        ),
        migrations.AlterField(
            model_name='respcytoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Respiratory/Cytology'),
        ),
        migrations.AlterField(
            model_name='resphistoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Respiratory/Histology'),
        ),
        migrations.AlterField(
            model_name='respimagingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Respiratory/Imaging'),
        ),
        migrations.AlterField(
            model_name='respmicroimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Respiratory/Microbiology'),
        ),
        migrations.AlterField(
            model_name='resppathoimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='Blocks/Respiratory/Pathology'),
        ),
        migrations.CreateModel(
            name='NeuroPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('neuroPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.NeuroPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('neuroMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.NeuroMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('neuroImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.NeuroImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('neuroHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.NeuroHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('neuroCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.NeuroCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='NeuroClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('neuroClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.NeuroClinicalImage')),
            ],
        ),
        migrations.CreateModel(
            name='MSKPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('mskPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.MSKPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='MSKMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('mskMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.MSKMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='MSKImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('mskImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.MSKImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='MSKHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('mskHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.MSKHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='MSKCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('mskCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.MSKCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='MSKClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('mskClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.MSKClinicalImage')),
            ],
        ),
        migrations.CreateModel(
            name='HemaPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('hemaPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.HemaPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='HemaMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('hemaMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.HemaMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='HemaImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('hemaImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.HemaImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='HemaHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('hemaHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.HemaHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='HemaCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('hemaCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.HemaCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='HemaClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('hemaClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.HemaClinicalImage')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('genitoPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GenitoPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('genitoMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GenitoMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('genitoImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GenitoImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('genitoHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GenitoHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('genitoCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GenitoCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='GenitoClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('genitoClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GenitoClinicalImage')),
            ],
        ),
        migrations.CreateModel(
            name='GastroPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('gastroPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GastroPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='GastroMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('gastroMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GastroMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='GastroImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('gastroImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GastroImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='GastroHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('gastroHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GastroHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='GastroCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('gastroCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GastroCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='GastroClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('gastroClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.GastroClinicalImage')),
            ],
        ),
        migrations.CreateModel(
            name='EndoPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('endoPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.EndoPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='EndoMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('endoMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.EndoMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='EndoImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('endoImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.EndoImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='EndoHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('endoHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.EndoHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='EndoCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('endoCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.EndoCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='EndoClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('endoClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.EndoClinicalImage')),
            ],
        ),
        migrations.CreateModel(
            name='CardioPathoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('cardioPathoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.CardioPathoImage')),
            ],
        ),
        migrations.CreateModel(
            name='CardioMicroNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('cardioMicroImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.CardioMicroImage')),
            ],
        ),
        migrations.CreateModel(
            name='CardioImagingNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('cardioImagingImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.CardioImagingImage')),
            ],
        ),
        migrations.CreateModel(
            name='CardioHistoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('cardioHistoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.CardioHistoImage')),
            ],
        ),
        migrations.CreateModel(
            name='CardioCytoNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('cardioCytoImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.CardioCytoImage')),
            ],
        ),
        migrations.CreateModel(
            name='CardioClinicalNotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('noteContent', models.TextField(blank=True, null=True)),
                ('x', models.IntegerField(blank=True, null=True)),
                ('y', models.IntegerField(blank=True, null=True)),
                ('cardioClinicalImage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='setNotes', to='backend.CardioClinicalImage')),
            ],
        ),
    ]
