# Generated by Django 3.2 on 2022-03-04 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('backend', '0025_auto_20220304_1350'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('site', models.TextField(blank=True, null=True)),
                ('onset', models.TextField(blank=True, null=True)),
                ('characteristics', models.TextField(blank=True, null=True)),
                ('radation', models.TextField(blank=True, null=True)),
                ('timing', models.TextField(blank=True, null=True)),
                ('factorsBetter', models.TextField(blank=True, null=True)),
                ('factorsWorse', models.TextField(blank=True, null=True)),
                ('criteria', models.TextField(blank=True, null=True)),
                ('extra1', models.TextField(blank=True, null=True)),
                ('extra2', models.TextField(blank=True, null=True)),
                ('extra3', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='complaint', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('complaints', models.ManyToManyField(blank=True, related_name='conditions', to='backend.Complaint')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='condition', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('mrn', models.TextField(blank=True, null=True)),
                ('patient_name', models.TextField(blank=True, null=True)),
                ('birth', models.CharField(blank=True, max_length=20, null=True)),
                ('owner_username', models.CharField(max_length=30, null=True)),
                ('complaints', models.ManyToManyField(blank=True, related_name='sessions', to='backend.Complaint')),
                ('conditions', models.ManyToManyField(blank=True, related_name='sessionsConditions', to='backend.Condition')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='session', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='set',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='setimage',
            name='set',
        ),
        migrations.RemoveField(
            model_name='setnotes',
            name='setImage',
        ),
        migrations.DeleteModel(
            name='Cluster',
        ),
        migrations.DeleteModel(
            name='Set',
        ),
        migrations.DeleteModel(
            name='SetImage',
        ),
        migrations.DeleteModel(
            name='SetNotes',
        ),
    ]
