# Generated by Django 3.0.3 on 2020-06-24 23:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microset',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MicrosSETT', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Micro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Micros', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
